- src/mria.erl
- test/mria_autoheal_SUITE.erl
Minor fix of the autoheal procedure
> fix(autoheal): Pass `heal' reason to the stop callback

- src/mria_status.erl
- test/concuerror_tests.erl
Fixes #17.
On some conditions, the `mria_status` `gen_event` server may receive a
`{'EXIT', From, Reason}` message from some linked process that has
called `mria_status`. Since `mria_status` does not currently implement
the `handle_info/2` callback, it crashes and logs a message like this:
```
** Undefined handle_info in mria_status
** Unhandled message: {'EXIT',<0.492.0>,shutdown}
```
By implementing the missing callback and just ignoring the unexpected
message, we avoid spamming the logs with messages like this.
> fix(status): Implement `handle_info/2` callback in mria_status

- Makefile
- rebar.config
- src/mria.erl
- src/mria_config.erl
- src/mria_lib.erl
- src/mria_rlog_agent.erl
- src/mria_rlog_replica.erl
- src/mria_status.erl
- test/concuerror_tests.erl
- test/mria_SUITE.erl
- test/mria_mnesia_test_util.erl
- test/mria_rlog_props.erl
Performance optimizations:
1. Forwarding of the TLOGs to the replicant nodes is made asynchronous (call -> cast)
2. Use a different TCP connection for each shard
Also some test fixes.
> Mulitple tcp connections

- src/mria.erl
- src/mria_activity.erl
There is very little reason to use nested transactions to capture TLOGs. Removing them will make code cleaner and possible slightly faster.
> fix(activity): Remove nested transactions

- src/mria_config.erl
- src/mria_lb.erl
- src/mria_lib.erl
- src/mria_mnesia.erl
- src/mria_rlog.erl
- test/mria_lb_SUITE.erl
- test/mria_mnesia_test_util.erl
Fixes #36 .
This adds a callback that can be registered to list the core nodes
instead of reading a fixed list from config.  This should help when
discovering core nodes via discovery mechanisms such as etcd, Consul
and others.
> feat(core_node_callback): add callback to enumerate core nodes

- rebar.config
This is a small change that disables liburing detection by default, since it's known to cause problems on some distributives.
> chore(rocksdb): Bump dependency

- src/mria_mnesia.erl
Fixes #49 .
Since `mria_node_monitor` calls `mria_mnesia:running_nodes/0`, and
there's a `rpc:multicall` contained in it, that can hang indefinetely,
making the former process' message queue bloat.
> fix(running_nodes): add timeout to `running_nodes`

- src/mria_lb.erl
- src/mria_status.erl
Some shards generate more traffic than the others. This PR will make sure that the agents belonging to the same shard are distributed equally. 
Fixes: #68
> fix(lb): Take shard into account when calculating weight

- src/mria_config.erl
- src/mria_lib.erl
- src/mria_replica_importer_worker.erl
- src/mria_rlog.hrl
- src/mria_rlog_replica.erl
When reading the data in the shard is only done using dirty operations, it doesn't make sense to go through the transaction mechanism during importing. This PR allows to mark the shard as "dirty", which means importing data to the shard is always done using dirty operations.
> feat: Batch transaction imports

- src/mria_mnesia.erl
- test/mria_mnesia_SUITE.erl
- test/mria_proper_mixed_cluster_suite.erl
- test/mria_proper_utils.erl
Fixes #75 .
Calling `mnesia:system_info(db_nodes)` on a replicant will return only
the replicant self node.  We need to check with the upstream core the
true list of all core nodes.
> fix: return cores from replicant

- Makefile
- include/mria.hrl
- src/mria_autoheal.erl
- src/mria_lb.erl
- src/mria_membership.erl
- src/mria_mnesia.erl
- src/mria_rlog.erl
- test/mria_autoheal_SUITE.erl
- test/mria_membership_SUITE.erl
- Adds the node role to the membership record.
- Consider only core nodes when listing nodes to consider for the autoheal / splitview feature.
- Only insert core nodes into the local membership table, so replicants don't get used as leaders nor coordinators.
> Fix: consider only core nodes in autoheal and in membership

- src/mria_lib.erl
- src/mria_shards_sup.erl
- src/mria_status.erl
- test/mria_autoheal_SUITE.erl
Also, reduces some message log levels about waiting for shards to
debug on cores, where such messages are not so useful.
> fix(txn): do not wait on shard during transaction

- src/mria.erl
- src/mria_replica_importer_worker.erl
- src/mria_rlog_server.erl
- test/mria_SUITE.erl
When I use `mria:create_table/2` to create a counter table and use `mneisa:dirty_update_counter/3` in the core node, I get the following error message:
```
v5.0.12-g020c43d8(core1@127.0.0.1)10> mria:create_table(counter_table, [{type, set},{rlog_shard, emqx_tenancy_shard}]).
ok
v5.0.12-g020c43d8(core1@127.0.0.1)11> mnesia:dirty_update_counter(counter_table, key, 1).
1
v5.0.12-g020c43d8(core1@127.0.0.1)12> 
2023-01-06T16:00:50.583580+08:00 [error] Generic server emqx_tenancy_shard terminating. Reason: {function_clause,[{mria_rlog_server,transform_op,[{{counter_table,key},{counter_table,1},update_counter}],[{file,"mria_rlog_server.erl"},{line,274}]},{mria_rlog_server,'-transform_commit/2-lc$^0/1-2-',2,[{file,"mria_rlog_server.erl"},{line,261}]},{maps,fold_1,3,[{file,"maps.erl"},{line,410}]}, …
```
> feat: support mnesia:dirty_update_counter/3

- src/mria_config.erl
- src/mria_lb.erl
- src/mria_schema.erl
- test/mria_SUITE.erl
- test/mria_ct.erl
- test/mria_lb_SUITE.erl
- test/mria_rlog_props.erl
Prior to this fix, the LB got pretty much stuck any time it detected a split in the core cluster. 
Now it does the following:
- Collects mnesia cluster view from all discovered core nodes 
- If the core cluster is partitioned, it tries to stick to a single partition, which is selected according to the following heuristics:
+ It contains most of the old core nodes
+ In case of a tie, it picks the biggest partition
> Handle the situation when one of the core nodes leaves the cluster

- rebar.config
- src/mria.erl
- src/mria_autoheal.erl
- src/mria_config.erl
- src/mria_membership.erl
- src/mria_mnesia.erl
- src/mria_node_monitor.erl
- src/mria_schema.erl
- src/mria_status.erl
- test/mria_SUITE.erl
- test/mria_membership_SUITE.erl
- test/mria_mnesia_SUITE.erl
Background:
Some time ago EMQX started using `mria_mnesia:running_nodes()` function instead of `erlang:nodes()` to avoid RPC'ing to remote shell nodes and other non-EMQX nodes that may appear in the cluster.
It required adding replicant nodes to the output of that function. I didn't think hard enough about the ramifications of such decision and went ahead with it. It created some nasty circular dependencies between the processes, that manifest themselves during restarts or cluster healing or joining.
This PR restores some sanity to the call graph. 
1) `mria_mnesia` no longer knows anything about RLOG processes
2) `mria_membership` no longer calls RLOG processes
3) Added some XREF checks to avoid future problems; they can be improved.
> Mria mnesia cleanup

- src/mria.erl
This will improve mria:r_transaction/2 performance when a caller process has a long message queue.
Closes: EMQX-9213
> feat: wrap mria ro_transaction with maybe_middleman/3

- src/mria.erl
- src/mria_membership.erl
- src/mria_replica_importer_worker.erl
- src/mria_rlog.erl
- src/mria_rlog.hrl
- src/mria_rlog_replica.erl
- src/mria_schema.erl
- src/mria_upstream.erl
- test/mria_SUITE.erl
When called on a replicant node, this function blocks a caller process until the transaction is replicated on that node or a timeout occurs. Otherwise, it behaves the same way as mria:transaction/3,2
Closes: EMQX-9102
> feat: implement mria:sync_transaction/4,3,2

- include/mria.hrl
- src/mria.erl
- test/mria_SUITE.erl
The lock must resolve conflicts between two nodes trying to join each other simultaneously
Fixes: EMQX-9588, #10380
> fix: protect 'join' operation with a global lock

- rebar.config
- src/mria_membership.erl
- test/mria_membership_SUITE.erl
This ensures mria_membership won't crash if RPC to another node fails.
> fix(mria_membership): call `mria_rlog:role/1` safely

- .github/workflows/run_test_case.yaml
- rebar.config
https://github.com/emqx/erlang-rocksdb/releases/tag/1.8.0-emqx-1
will tag 0.5.8
> chore: bump `mnesia_rocksdb` -> 0.1.14

- src/mria_bootstrapper.erl
- src/mria_config.erl
Increasing batch size seems to improve performance over high latency network.
> feat: make bootstrap batch size configurable per shard

- src/mria_status.erl
```
Run stage failed: error:{exception,badarith,
[{erlang,'-',
[5,undefined],
[{error_info,#{module => erl_erts_errors}}]},
{mria_status,get_shard_lag,1,
[{file,"/__w/mria/mria/src/mria_status.erl"},
{line,187}]},
{mria_status,get_shard_stats,1,
[{file,"/__w/mria/mria/src/mria_status.erl"},
{line,256}]},
{mria_rlog,'-status/0-lc$^0/1-0-',1,
[{file,"/__w/mria/mria/src/mria_rlog.erl"},
{line,99}]},
{mria_rlog,status,0,
[{file,"/__w/mria/mria/src/mria_rlog.erl"},
{line,100}]},
{mria,info,0,
[{file,"/__w/mria/mria/src/mria.erl"},
{line,157}]},
{mria,do_join,3,
[{file,"/__w/mria/mria/src/mria.erl"},
{line,606}]},
{global,trans,4,
[{file,"global.erl"},{line,477}]}]}
```
https://github.com/emqx/mria/actions/runs/6201007103/job/16836825159?pr=160#step:10:19086
> fix(status): don't subtract `undefined` when calculating shard lag

- src/mria_config.erl
- src/mria_mnesia.erl
- test/mria_mnesia_SUITE.erl
Part of https://emqx.atlassian.net/browse/EMQX-10944
> feat: add custom diagnostic checks when mnesia is stuck

- src/mria_config.erl
Since this is a hidden, optional configuration that doesn't affect normal operations, users shouldn't be alarmed by a misconfiguration.
> chore: reduce diagnosts config check log level

- rebar.config
upgrade:
- mnesia_rocksdb to `0.1.15`
- erlang-rocksdb to `1.8.0-emqx-2`
> chore: upgrade to mnesia_rocksdb 0.1.15 for OTP 26 support

- src/mria.erl
- src/mria_replica_importer_worker.erl
- test/mria_SUITE.erl
The check is done on a local node, assuming that all nodes in the cluster run the same OTP/Mnesia.
> check that Mnesia supports match_delete/2

- src/mria_membership.erl
For example, if a node has just joined the cluster, but has not fully rebooted successfully, its `guid` is undefined:
```
[{member,'emqx@10.42.3.236',undefined,
<<0,6,15,187,202,198,177,159,90,134,0,0,11,232,
0,0>>,
3792610979,up,running,
{1706,149095,584199},
core},
{member,'emqx@10.42.6.225',undefined,undefined,
undefined,up,running,
{1706,155167,852643},
core}]
```
> fix(membership): leader calculation error in some cases

- src/mria_rlog.hrl
- src/mria_schema.erl
- test/mria_mnesia_SUITE.erl
In specific circumstances `mria_mnesia:copy_table/2` may fail with `{system_limit, '$mria_rlog_sync', {Node, none_active}}` error, which crashes the node.
Consider the following scenario:
1. Node `N1` starts up and bootstraps Mria.
2. Node `N2` starts up and bootstraps Mria.
3. Node `N2` joins cluster consisting of node `N1`.
4. Node `N2` runs `mria_mnesia:join_cluster/1` and starts Mria again.
5. At the exact same time node `N1` decides to restart for some reason.
6. During bootstrap, node `N2` tries to copy `$mria_rlog_sync` table.
7. Mnesia sees there's nowhere to copy from and aborts the operation.
8. Mria fails to start.
While unlikely, in practice this might be achieved when the operator performs unusual maintenance operations, e.g. simultaneously requests version upgrade and scales …
> fix(bootstrap): wait core tables are ready before copying

- include/mria.hrl
- rebar.config
- src/mria.erl
- src/mria_mnesia.erl
- test/mria_SUITE.erl
See individual commits for details.
Fixes [EMQX-13588](https://emqx.atlassian.net/browse/EMQX-13588).
> fix: make global lock guarding join operations stricter

- src/mria.erl
- src/mria_rlog_replica.erl
- src/mria_status.erl
- test/concuerror_tests.erl
- test/mria_SUITE.erl
- test/mria_lb_SUITE.erl
Introduce a new optvar for RPC targeting instead of trying to reuse others.
> fix(rpc): Follow-up to the previous fix

- src/mria.erl
- src/mria_core_shard_sup.erl
- src/mria_lb.erl
- src/mria_rebalance.erl
- src/mria_rlog.erl
- test/mria_SUITE.erl
Implement `mria_rebalance` module that allows to schedule rebalancing of replicant agents among the core nodes semi-automatically.
> feat(rebalance): Implement core node rebalancing

- src/mria.erl
- src/mria_lib.erl
- test/mria_SUITE.erl
This way we avoid polluting message queue of the calling process with `{'EXIT', ..., normal}` messages in case when the calling process is trapping exits.
Selective receive optimization is preserved.
```
src/mria.erl:543: OPTIMIZED: reference used to mark a message queue position
src/mria.erl:551: OPTIMIZED: all clauses match reference created by spawn_monitor/1 at ws/emqx/mria/src/mria.erl:543
```
> fix: run middleman through spawn_monitor/1
